#!/usr/bin/env bash
# configure_ap.sh — idempotently set up the Raspberry Pi as a WLAN access point.
#
# Uses hostapd + dnsmasq (most robust, well-automated combo on current
# Raspberry Pi OS). NetworkManager is NOT used for the AP interface to avoid
# conflicts. The script is safe to run multiple times.
#
# Usage:
#   sudo ./configure_ap.sh [--ssid NAME] [--password PWD] [--gateway IP] \
#                          [--dhcp-start IP] [--dhcp-end IP] [--channel N] \
#                          [--country DE] [--interface wlan0]
#
# All arguments are optional and override values from a config file
# (/etc/rmx-sx-gateway/gateway.yaml) if present.
set -euo pipefail

SSID="Modellbahn-Fahrregler"
PASSWORD="bitte-aendern"
GATEWAY="192.168.50.1"
NETWORK="192.168.50.0/24"
DHCP_START="192.168.50.100"
DHCP_END="192.168.50.200"
CHANNEL="6"
COUNTRY="DE"
IFACE="wlan0"
CONFIG_FILE="/etc/rmx-sx-gateway/gateway.yaml"

# --- parse overrides -------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ssid)       SSID="$2"; shift 2;;
    --password)   PASSWORD="$2"; shift 2;;
    --gateway)    GATEWAY="$2"; shift 2;;
    --network)    NETWORK="$2"; shift 2;;
    --dhcp-start) DHCP_START="$2"; shift 2;;
    --dhcp-end)   DHCP_END="$2"; shift 2;;
    --channel)    CHANNEL="$2"; shift 2;;
    --country)    COUNTRY="$2"; shift 2;;
    --interface)  IFACE="$2"; shift 2;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root (sudo)." >&2
  exit 1
fi

if [[ -f "$CONFIG_FILE" ]]; then
  echo "Reading defaults from $CONFIG_FILE (CLI args override)."
  # crude YAML extraction, safe because values are single-quoted/double-quoted
  _get() { grep -E "^[[:space:]]*$1:" "$CONFIG_FILE" | head -1 | sed -E 's/.*:[[:space:]]*"?([^"#]+)"?.*/\1/' | tr -d ' '; }
  _v=$(_get "ssid");        [[ -n "$_v" ]] && SSID="$_v"
  _v=$(_get "gateway");     [[ -n "$_v" ]] && GATEWAY="$_v"
  _v=$(_get "dhcp_start");  [[ -n "$_v" ]] && DHCP_START="$_v"
  _v=$(_get "dhcp_end");    [[ -n "$_v" ]] && DHCP_END="$_v"
  _v=$(_get "channel");     [[ -n "$_v" ]] && CHANNEL="$_v"
  _v=$(_get "country");     [[ -n "$_v" ]] && COUNTRY="$_v"
  _v=$(_get "interface");   [[ -n "$_v" ]] && IFACE="$_v"
fi

if [[ ${#PASSWORD} -lt 8 ]]; then
  echo "WARNING: WPA2 password should be at least 8 characters." >&2
fi

echo "=== Configuring AP: SSID=$SSID IFACE=$IFACE GW=$GATEWAY ==="

# --- install packages (idempotent) -----------------------------------------
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y hostapd dnsmasq

# Prevent dnsmasq from being started by its own init before we configure it.
systemctl unmask hostapd dnsmasq 2>/dev/null || true

# --- static IP for the AP interface ----------------------------------------
backup_dir="/var/backups/rmx-sx-gateway/$(date +%Y%m%d-%H%M%S)"
mkdir -p "$backup_dir"
cp -a /etc/dhcpcd.conf "$backup_dir/" 2>/dev/null || true
cp -a /etc/network/interfaces "$backup_dir/" 2>/dev/null || true

DHCPCD_CONF="/etc/dhcpcd.conf"
if ! grep -q "interface $IFACE" "$DHCPCD_CONF"; then
  cat >> "$DHCPCD_CONF" <<EOF

# --- rmx-sx-gateway AP (added by configure_ap.sh) ---
interface $IFACE
    static ip_address=$GATEWAY/24
    nohook wpa_supplicant
EOF
fi

# --- hostapd config ---------------------------------------------------------
HOSTAPD_CONF="/etc/hostapd/hostapd.conf"
cat > "$HOSTAPD_CONF" <<EOF
# Generated by configure_ap.sh — RMX/SX WLAN Gateway
country_code=$COUNTRY
interface=$IFACE
ssid=$SSID
hw_mode=g
channel=$CHANNEL
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=$PASSWORD
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
EOF

if [[ -f /etc/default/hostapd ]]; then
  sed -i 's|^#\?DAEMON_CONF=.*|DAEMON_CONF="/etc/hostapd/hostapd.conf"|' /etc/default/hostapd
fi

# --- dnsmasq config ---------------------------------------------------------
DNSMASQ_CONF="/etc/dnsmasq.d/rmx-sx-gateway.conf"
cat > "$DNSMASQ_CONF" <<EOF
# Generated by configure_ap.sh — RMX/SX WLAN Gateway
interface=$IFACE
bind-interfaces
dhcp-range=$DHCP_START,$DHCP_END,12h
dhcp-option=option:router,$GATEWAY
dhcp-option=option:dns-server,$GATEWAY
no-resolv
EOF

# --- enable & restart services ---------------------------------------------
systemctl enable hostapd dnsmasq
systemctl restart hostapd dnsmasq

echo "=== AP configuration complete. ==="
echo "SSID: $SSID"
echo "Gateway IP: $GATEWAY"
echo "DHCP range: $DHCP_START - $DHCP_END"
echo "Verify with: sudo ./status.sh"
